fix and recactor splits and add more tests
4e554c4c/list_cursors pull request #1
Opened 2018-10-27 13:44 UTC by xaberus

This fixes splits and refactors them to have a common code path. I also extended the tests to catch some corner cases and added a rudimentary checking for dangling links in `cmp_iterator(...)`

2018-10-27 21:20 UTC, 4e554c4c requested changes
Nice work! Thank you. Just a few comments.

2018-10-27 21:20 UTC, 4e554c4c commented on src/lib.rs
> +            None => replace(self.list, LinkedList::new()),
Should this be the case? I think that if the current element is the empty element then the returned list should be empty.
This is because suppose someone has a cursor to the last element and calls split, this would return the empty list. This should be the same behavior as if one moved the cursor ahead one and called `split_before`.

2018-10-27 21:20 UTC, 4e554c4c commented on src/lib.rs
> +                c.split_before()
How do these test split when the returned list is not compared?

2018-10-28 10:55 UTC, xaberus commented on src/lib.rs
> +            None => replace(self.list, LinkedList::new()),
@4e554c4c: I think it depends on what we mean by before/after. Maybe it is a good idea to differentiate between before first/after last element... My reasoning went along: when we create a cursor, then `next()` will give the first element, so split should return all of the elements, draining the original list. Of course when we are iterating from behind it makes more sense to return an empty list

2018-10-28 10:58 UTC, xaberus commented on src/lib.rs
> +                c.split_before()
Sorry, I did not understand your question... The equality test is performed in lines 616-621, if that is what you meant.

2018-10-28 16:31 UTC, 4e554c4c commented on src/lib.rs
> +                c.split_before()
yes... sorry I missed this somehow

2018-10-28 16:34 UTC, 4e554c4c commented on src/lib.rs
> +            None => replace(self.list, LinkedList::new()),
fair. This is ambiguous in the rfc, so it should be resolved there.

2018-10-28 16:34 UTC, 4e554c4c approved these changes

2018-10-28 16:34 UTC, merged

2018-10-28 16:35 UTC, 4e554c4c commented
Thanks!